import { useState } from "react";
import { Eye, EyeOff, Pencil, Plus, Search, Trash2, UserRound, X } from "lucide-react";
import { deleteSiswaRecord, getSiswaList, saveSiswaRecord, statusBadgeColor, type SiswaRecord } from "@/data/siswaStore";

export default function DataSiswaList({ searchValue = "", onAdd }: { searchValue?: string; onAdd?: () => void }) {
  const [version, setVersion] = useState(0);
  const [showPasswords, setShowPasswords] = useState(false);
  const [selected, setSelected] = useState<SiswaRecord | null>(null);
  const [query, setQuery] = useState(searchValue);
  const list = getSiswaList().filter((student) => `${student.namaLengkap} ${student.nisn} ${student.kelas}`.toLowerCase().includes(query.toLowerCase()));
  const refresh = () => setVersion((value) => value + 1);

  return <div className="space-y-4 rounded-2xl border border-border bg-card p-5 shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-bold">Daftar Siswa</h3><p className="text-sm text-muted-foreground">{list.length} siswa terdaftar</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setShowPasswords((value) => !value)} className="flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-xs font-semibold text-muted-foreground hover:bg-muted">{showPasswords ? <EyeOff size={15} /> : <Eye size={15} />}{showPasswords ? "Sembunyikan Sandi" : "Tampilkan Status Sandi"}</button><button type="button" onClick={onAdd} className="flex items-center gap-2 rounded-xl bg-[hsl(var(--guru-sapphire))] px-4 py-2.5 text-xs font-bold text-primary-foreground hover:brightness-105"><Plus size={15} /> Input Data Siswa</button></div></div>
    <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama, NIS, atau kelas..." className="w-full rounded-xl border border-input bg-muted/30 py-3 pl-10 pr-4 text-sm outline-none focus:border-[hsl(var(--guru-sapphire))]" /></div>
    <div className="overflow-x-auto rounded-xl border border-border"><table className="min-w-[1120px] w-full text-xs"><thead><tr className="border-b border-border bg-muted/50 text-left text-[11px] font-bold text-muted-foreground">{["NIS","Nama","Kelas","L/P","Kontak","User Siswa","Sandi Siswa","User Ortu","Sandi Ortu","Status","Aksi"].map((heading) => <th key={heading} className="whitespace-nowrap px-3 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{list.map((student) => <tr key={student.kodeSiswa} className="hover:bg-muted/30"><td className="px-3 py-3 font-mono text-muted-foreground">{student.nis || student.nisn || "—"}</td><td className="px-3 py-3 font-bold">{student.namaLengkap}</td><td className="px-3 py-3">{student.kelas || "—"}</td><td className="px-3 py-3">{student.jenisKelamin === "Perempuan" ? "P" : "L"}</td><td className="px-3 py-3 text-muted-foreground">{student.teleponWali || student.telepon || "—"}</td><td className="px-3 py-3 font-mono">{student.usernameSiswa || "—"}</td><td className="px-3 py-3 font-mono text-muted-foreground">{showPasswords ? "Tersedia" : "••••••••"}</td><td className="px-3 py-3 font-mono">{student.usernameOrtu || "—"}</td><td className="px-3 py-3 font-mono text-muted-foreground">{showPasswords ? "Tersedia" : "••••••••"}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusBadgeColor[student.status] || "bg-muted text-muted-foreground"}`}>{student.status}</span></td><td className="px-3 py-3"><div className="flex gap-1"><button type="button" aria-label="Edit siswa" onClick={() => setSelected(student)} className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil size={14} /></button><button type="button" aria-label="Hapus siswa" onClick={() => { if (window.confirm(`Hapus ${student.namaLengkap}?`)) { deleteSiswaRecord(student.kodeSiswa); refresh(); } }} className="rounded-lg p-1.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 size={14} /></button></div></td></tr>)}</tbody></table>{list.length === 0 && <div className="p-10 text-center text-sm text-muted-foreground">Tidak ada siswa yang cocok dengan pencarian.</div>}</div>
    {selected && <EditStudent student={selected} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); refresh(); }} />}
  </div>;
}

function EditStudent({ student, onClose, onSaved }: { student: SiswaRecord; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(student.namaLengkap);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-5 shadow-2xl"><div className="flex items-center justify-between"><h3 className="font-bold">Edit Data Siswa</h3><button type="button" aria-label="Tutup" onClick={onClose}><X size={18} /></button></div><label className="mt-5 block text-xs font-semibold">Nama Lengkap<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-xl border border-input bg-muted/40 px-3 py-2.5 text-sm" /></label><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><p><span className="text-muted-foreground">NIS</span><br /><b>{student.nis || "—"}</b></p><p><span className="text-muted-foreground">Kelas</span><br /><b>{student.kelas}</b></p></div><button type="button" onClick={() => { saveSiswaRecord({ ...student, namaLengkap: name }); onSaved(); }} className="mt-5 w-full rounded-xl bg-[hsl(var(--guru-sapphire))] py-3 font-semibold text-primary-foreground">Simpan Perubahan</button></div></div>;
}