import { useState } from "react";
import { Eye, KeyRound, Pencil, RotateCcw, Trash2, X } from "lucide-react";
import { deleteGuruRecord, getGuruByJenis, jenisBadgeColor, jenisLabel, saveGuruRecord, type GuruRecord, type JenisGuru } from "@/data/guruStore";

export default function DataGuruList({ jenis, searchValue = "" }: { jenis: JenisGuru; searchValue?: string }) {
  const [version, setVersion] = useState(0);
  const [editing, setEditing] = useState<GuruRecord | null>(null);
  const list = getGuruByJenis(jenis).filter((guru) => `${guru.namaLengkap} ${guru.kodeGuru} ${guru.mataPelajaran}`.toLowerCase().includes(searchValue.toLowerCase()));
  return <div className="rounded-2xl border border-border bg-card shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-5"><div><h3 className="font-bold text-foreground">{jenisLabel[jenis]}</h3><p className="text-sm text-muted-foreground">{list.length} guru terdaftar</p></div><div className="flex items-center gap-2 rounded-xl bg-muted/40 px-3 py-2 text-xs text-muted-foreground"><Eye size={14} /> Password selalu masked</div></div><div className="overflow-x-auto"><table className="min-w-[920px] w-full text-sm"><thead><tr className="border-b border-border bg-muted/50 text-left text-xs uppercase text-muted-foreground">{["Kode Guru", "Nama", "NIP", "Mata Pelajaran", "User Guru", "Sandi", "Aksi"].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{list.map((guru) => <tr key={guru.kodeGuru} className="hover:bg-muted/30"><td className="px-4 py-3"><span className={`rounded-lg px-2 py-1 text-xs font-bold ${jenisBadgeColor[guru.jenisGuru]}`}>{guru.kodeGuru}</span></td><td className="px-4 py-3 font-medium">{guru.namaLengkap}</td><td className="px-4 py-3 text-muted-foreground">{guru.nip || "—"}</td><td className="px-4 py-3">{guru.mataPelajaran || "—"}</td><td className="px-4 py-3 font-mono text-xs">{guru.usernameGuru || "—"}</td><td className="px-4 py-3 font-mono text-xs text-muted-foreground">••••••••</td><td className="px-4 py-3"><div className="flex gap-1"><button type="button" aria-label="Edit guru" onClick={() => setEditing(guru)} className="rounded-lg p-1.5 text-amber-500 hover:bg-amber-500/10"><Pencil className="h-4 w-4" /></button><button type="button" aria-label="Reset password" onClick={() => window.alert("Reset password akan diproses melalui backend setelah autentikasi admin aktif.")} className="rounded-lg p-1.5 text-[hsl(var(--guru-sapphire))] hover:bg-primary/10"><RotateCcw className="h-4 w-4" /></button><button type="button" aria-label="Hapus guru" onClick={() => { if (window.confirm(`Hapus ${guru.kodeGuru}?`)) { deleteGuruRecord(guru.kodeGuru); setVersion((value) => value + 1); } }} className="rounded-lg p-1.5 text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table>{list.length === 0 && <div className="p-10 text-center text-sm text-muted-foreground">Belum ada data {jenisLabel[jenis]}.</div>}</div>{editing && <EditGuru guru={editing} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); setVersion((value) => value + 1); }} />}</div>;
}

function EditGuru({ guru, onClose, onSaved }: { guru: GuruRecord; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(guru.namaLengkap);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-5 shadow-2xl"><div className="flex items-center justify-between"><h3 className="font-bold">Edit Data Guru</h3><button type="button" aria-label="Tutup" onClick={onClose}><X size={18} /></button></div><label className="mt-5 block text-sm">Nama Lengkap<input value={name} onChange={(event) => setName(event.target.value)} className="mt-1 w-full rounded-xl border border-input bg-muted/40 px-3 py-2.5" /></label><div className="mt-4 flex items-center gap-2 rounded-xl bg-muted/40 p-3 text-xs text-muted-foreground"><KeyRound size={14} /> Username: {guru.usernameGuru || "belum dibuat"} · Password: masked</div><button type="button" onClick={() => { saveGuruRecord({ ...guru, namaLengkap: name }); onSaved(); }} className="mt-5 w-full rounded-xl bg-primary py-2.5 font-semibold text-primary-foreground">Simpan Perubahan</button></div></div>;
}
