import { useState } from "react";
import { ArrowLeft, Eye, EyeOff, KeyRound, UserPlus } from "lucide-react";
import { addSiswaRecord, kelasOptions, nextKodeSiswa, type SiswaRecord } from "@/data/siswaStore";

export default function InputSiswa({ onSaved, onCancel }: { onSaved: () => void; onCancel?: () => void }) {
  const [form, setForm] = useState({ nis: "", namaLengkap: "", kelas: "", jenisKelamin: "Laki-laki", emailWali: "", teleponWali: "", usernameSiswa: "", passwordSiswa: "", usernameOrtu: "", passwordOrtu: "" });
  const [error, setError] = useState("");
  const set = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const save = () => {
    if (!form.nis.trim() || !form.namaLengkap.trim() || !form.kelas || !form.usernameSiswa.trim() || !form.passwordSiswa || !form.usernameOrtu.trim() || !form.passwordOrtu) { setError("Lengkapi semua field wajib yang bertanda *."); return; }
    const record: SiswaRecord = { kodeSiswa: nextKodeSiswa(), createdAt: new Date().toISOString(), namaLengkap: form.namaLengkap, nis: form.nis, nisn: "", nik: "", tempatLahir: "", tanggalLahir: "", jenisKelamin: form.jenisKelamin, agama: "", telepon: "", email: "", alamat: "", kota: "", provinsi: "", kelas: form.kelas, tahunMasuk: "", namaWali: "", hubunganWali: "", teleponWali: form.teleponWali, usernameSiswa: form.usernameSiswa, usernameOrtu: form.usernameOrtu, status: "Aktif" };
    addSiswaRecord(record); onSaved();
  };
  const field = (label: string, key: keyof typeof form, placeholder: string, required = false) => <label className="block text-xs font-semibold">{label}{required && <span className="text-destructive"> *</span>}<input value={form[key]} onChange={(event) => set(key, event.target.value)} placeholder={placeholder} className="mt-1.5 w-full rounded-xl border border-input bg-muted/30 px-3.5 py-3 text-sm font-normal outline-none focus:border-[hsl(var(--guru-sapphire))]" /></label>;

  return <div className="mx-auto max-w-4xl space-y-4"><button type="button" onClick={onCancel ?? onSaved} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={15} /> Kembali ke Daftar Siswa</button><section className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--guru-sapphire-soft))] text-[hsl(var(--guru-sapphire))]"><UserPlus size={20} /></span><div><h2 className="text-lg font-bold">Input Data Siswa</h2><p className="text-sm text-muted-foreground">Tambahkan siswa baru ke sistem MIRAI</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{field("NIS", "nis", "Nomor Induk Siswa", true)}{field("Nama Lengkap", "namaLengkap", "Nama lengkap siswa", true)}<label className="block text-xs font-semibold">Kelas<select value={form.kelas} onChange={(event) => set("kelas", event.target.value)} className="mt-1.5 w-full rounded-xl border border-input bg-muted/30 px-3.5 py-3 text-sm font-normal"><option value="">Pilih kelas</option>{kelasOptions.map((kelas) => <option key={kelas}>{kelas}</option>)}</select></label><label className="block text-xs font-semibold">Jenis Kelamin<select value={form.jenisKelamin} onChange={(event) => set("jenisKelamin", event.target.value)} className="mt-1.5 w-full rounded-xl border border-input bg-muted/30 px-3.5 py-3 text-sm font-normal"><option>Laki-laki</option><option>Perempuan</option></select></label>{field("Email Wali", "emailWali", "email wali siswa")}{field("Nomor Telepon Wali", "teleponWali", "08xxxxxxxxxx")}</div><AccountPanel title="Akun Login Siswa" usernameKey="usernameSiswa" passwordKey="passwordSiswa" value={form.passwordSiswa} onPasswordChange={(value) => set("passwordSiswa", value)} usernamePlaceholder="Username untuk login siswa" passwordPlaceholder="Password awal siswa" field={field} /><AccountPanel title="Akun Login Orang Tua" usernameKey="usernameOrtu" passwordKey="passwordOrtu" value={form.passwordOrtu} onPasswordChange={(value) => set("passwordOrtu", value)} usernamePlaceholder="Username untuk login orang tua" passwordPlaceholder="Password awal orang tua" field={field} /><div className="mt-6 flex flex-wrap items-center gap-3 border-t border-border pt-5">{error && <p className="mr-auto text-sm text-destructive">{error}</p>}<button type="button" onClick={onCancel ?? onSaved} className="rounded-xl border border-border px-5 py-3 text-sm font-semibold text-muted-foreground">Batal</button><button type="button" onClick={save} className="rounded-xl bg-[hsl(var(--guru-sapphire))] px-6 py-3 text-sm font-bold text-primary-foreground">Simpan Data Siswa</button></div></section></div>;
}

function AccountPanel({ title, usernameKey, passwordKey, value, onPasswordChange, usernamePlaceholder, passwordPlaceholder, field }: { title: string; usernameKey: "usernameSiswa" | "usernameOrtu"; passwordKey: "passwordSiswa" | "passwordOrtu"; value: string; onPasswordChange: (value: string) => void; usernamePlaceholder: string; passwordPlaceholder: string; field: (label: string, key: "usernameSiswa" | "usernameOrtu" | "passwordSiswa" | "passwordOrtu", placeholder: string, required?: boolean) => JSX.Element }) {
  const [showPassword, setShowPassword] = useState(false);
  return <section className="mt-5 rounded-xl border border-border bg-muted/20 p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><KeyRound size={16} className="text-[hsl(var(--guru-sapphire))]" />{title}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("Username", usernameKey, usernamePlaceholder, true)}<label className="block text-xs font-semibold">Password <span className="text-destructive">*</span><div className="relative mt-1.5"><input value={value} onChange={(event) => onPasswordChange(event.target.value)} name={passwordKey} placeholder={passwordPlaceholder} type={showPassword ? "text" : "password"} className="w-full rounded-xl border border-input bg-muted/30 px-3.5 py-3 pr-10 text-sm font-normal outline-none focus:border-[hsl(var(--guru-sapphire))]" /><button type="button" onClick={() => setShowPassword((current) => !current)} aria-label={showPassword ? "Sembunyikan password" : "Lihat password"} className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground">{showPassword ? <EyeOff size={15} /> : <Eye size={15} />}</button></div></label></div><p className="mt-2 text-[10px] italic text-muted-foreground">Password akan disimpan aman dan hanya dapat dilihat sebagai masked setelah akun dibuat.</p></section>;
}
