import { useEffect, useState } from "react";
import { LogOut } from "lucide-react";
import Sidebar from "@/components/guru/Sidebar";
import Topbar from "@/components/guru/Topbar";
import MobileBottomNav from "@/components/guru/MobileBottomNav";
import MobileDrawer from "@/components/guru/MobileDrawer";
import Beranda from "./guru/Beranda";
import ProfilGuru from "./guru/ProfilGuru";
import PlaceholderPage from "./guru/PlaceholderPage";
import { breadcrumbMap, navItems } from "@/components/guru/navConfig";
import { defaultProfileData } from "@/data/guruData";
const STORAGE_KEY="mirai_sidebar_collapsed";
export default function GuruDashboard(){const [active,setActive]=useState("beranda");const [collapsed,setCollapsed]=useState(()=>localStorage.getItem(STORAGE_KEY)==="true");const [drawer,setDrawer]=useState(false);useEffect(()=>{const mq=window.matchMedia("(min-width: 1024px)");const handler=(event:MediaQueryListEvent)=>{if(event.matches)setDrawer(false)};mq.addEventListener("change",handler);return()=>mq.removeEventListener("change",handler)},[]);const navigate=(id:string)=>{setActive(id);setDrawer(false);window.scrollTo(0,0)};const initials=defaultProfileData.namaLengkap.split(" ").map(part=>part[0]).slice(0,2).join("").toUpperCase();const Icon=navItems.find(item=>item.id===active)?.icon;const content=active==="beranda"?<Beranda onNavigate={navigate}/>:active==="profil-guru"?<ProfilGuru/>:<PlaceholderPage title={breadcrumbMap[active]??active} icon={Icon}/>;return <div className="flex h-screen flex-col overflow-hidden bg-[hsl(var(--guru-sapphire-soft))]"><div className="flex min-h-0 flex-1"><div className="hidden h-full lg:flex"><Sidebar activeItem={active} onNavigate={navigate} collapsed={collapsed} onToggleCollapse={()=>setCollapsed(value=>{const next=!value;localStorage.setItem(STORAGE_KEY,String(next));return next})}/></div><div className="flex min-h-0 min-w-0 flex-1 flex-col"><Topbar activeItem={active} onMobileMenuToggle={()=>setDrawer(true)} onNavigate={navigate} collapsed={collapsed} onToggleSidebar={()=>setCollapsed(value=>{const next=!value;localStorage.setItem(STORAGE_KEY,String(next));return next})} initials={initials}/><main className="flex-1 overflow-y-auto px-4 py-4 pb-20 lg:px-6 lg:py-6 lg:pb-6">{content}</main></div></div><footer className="flex shrink-0 items-center justify-between border-t border-white/10 bg-[hsl(var(--mirai-sidebar))] px-5 py-3 text-sm"><div className="flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-white/15 text-xs font-bold text-white">{initials}</div><div><div className="flex items-center gap-2"><span className="text-xs font-semibold text-white">{defaultProfileData.namaLengkap}</span><span className="rounded bg-white/20 px-1.5 py-0.5 font-mono text-[10px] font-bold text-white">{defaultProfileData.kodeGuru}</span></div><div className="text-[11px] text-white/60">{defaultProfileData.mataPelajaran} · Kelas 7 SMP</div></div></div><button type="button" onClick={()=>window.location.assign("/")} className="flex items-center gap-1.5 text-xs text-white/70 hover:text-white"><LogOut size={14}/> Keluar</button></footer><MobileDrawer open={drawer} onClose={()=>setDrawer(false)} activeItem={active} onNavigate={navigate}/><MobileBottomNav activeItem={active} onNavigate={navigate}/></div>}
