import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const corsHeaders = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type" };
const db = createClient(Deno.env.get("SUPABASE_URL") || "", Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "");
type Body = { action: "list" | "create" | "update" | "delete" | "publish" | "add-material" | "delete-material" | "add-assignment" | "delete-assignment"; id?: string; teacherId?: string; meetingNumber?: number; className?: string; title?: string; startsAt?: string; endsAt?: string; status?: "draft" | "published" | "locked"; material?: { title: string; kind: "file" | "link"; fileUrl?: string; fileName?: string; externalUrl?: string }; assignment?: { title: string; description?: string; dueAt?: string } };
Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {
    const token = request.headers.get("Authorization")?.replace("Bearer ", ""); if (!token) return json({ error: "Unauthorized" }, 401);
    const { data: auth, error: authError } = await db.auth.getUser(token); const user = auth.user; if (authError || !user) return json({ error: "Sesi tidak valid." }, 401);
    const body = await request.json() as Body; const role = user.app_metadata?.role as string | undefined;
    if (body.action === "list") { let query = db.from("class_meetings").select("*, meeting_materials(*), meeting_assignments(*)").order("meeting_number"); if (role === "teacher") { const { data: account } = await db.from("teacher_accounts").select("teacher_id").eq("auth_user_id", user.id).maybeSingle(); if (!account) return json({ meetings: [] }); query = query.eq("teacher_id", account.teacher_id); } else if (role !== "admin") { const { data: account } = await db.from("student_accounts").select("student_id").eq("auth_user_id", user.id).maybeSingle(); const { data: profile } = account ? await db.from("student_profiles").select("class_name").eq("id", account.student_id).maybeSingle() : { data: null }; if (!profile) return json({ meetings: [] }); query = query.eq("class_name", profile.class_name).eq("status", "published"); } const { data, error } = await query; if (error) return json({ error: error.message }, 400); return json({ meetings: data || [] }); }
    if (role !== "teacher" && role !== "admin") return json({ error: "Akses guru diperlukan." }, 403);
    if (body.action === "add-material" || body.action === "add-assignment" || body.action === "delete-material" || body.action === "delete-assignment") { if (!body.id) return json({ error: "ID meeting wajib diisi." }, 400); if (body.action === "add-material" && body.material?.title) { const { data, error } = await db.from("meeting_materials").insert({ meeting_id: body.id, title: body.material.title, kind: body.material.kind, file_url: body.material.fileUrl || null, file_name: body.material.fileName || null, external_url: body.material.externalUrl || null }).select().single(); if (error) return json({ error: error.message }, 400); return json({ ok: true, material: data }); } if (body.action === "add-assignment" && body.assignment?.title) { const { data, error } = await db.from("meeting_assignments").insert({ meeting_id: body.id, title: body.assignment.title, description: body.assignment.description || null, due_at: body.assignment.dueAt || null }).select().single(); if (error) return json({ error: error.message }, 400); return json({ ok: true, assignment: data }); } const table = body.action === "delete-material" ? "meeting_materials" : "meeting_assignments"; const { error } = await db.from(table).delete().eq("id", body.id); if (error) return json({ error: error.message }, 400); return json({ ok: true }); }
    if (body.action === "delete" || body.action === "publish") { if (!body.id) return json({ error: "ID meeting wajib diisi." }, 400); const values = body.action === "publish" ? { status: "published", updated_at: new Date().toISOString() } : null; const result = values ? await db.from("class_meetings").update(values).eq("id", body.id).select().single() : await db.from("class_meetings").delete().eq("id", body.id); if (result.error) return json({ error: result.error.message }, 400); return json({ ok: true, meeting: result.data }); }
    if (!body.title || !body.className || !body.startsAt || !body.endsAt || !body.meetingNumber || new Date(body.endsAt) <= new Date(body.startsAt)) return json({ error: "Judul, kelas, nomor, dan waktu yang valid wajib diisi." }, 400); let teacherId = body.teacherId; if (role === "teacher") { const { data: account } = await db.from("teacher_accounts").select("teacher_id").eq("auth_user_id", user.id).maybeSingle(); teacherId = account?.teacher_id; } if (!teacherId) return json({ error: "Profil guru belum terhubung." }, 400); const values = { teacher_id: teacherId, meeting_number: body.meetingNumber, class_name: body.className, title: body.title, starts_at: body.startsAt, ends_at: body.endsAt, status: body.status || "draft", updated_at: new Date().toISOString() }; const result = body.action === "update" && body.id ? await db.from("class_meetings").update(values).eq("id", body.id).select().single() : await db.from("class_meetings").insert(values).select().single(); if (result.error) return json({ error: result.error.message }, 400); return json({ ok: true, meeting: result.data });
  } catch (error) { console.error("class-meetings error", error instanceof Error ? error.message : "unknown"); return json({ error: "Layanan pertemuan mengalami gangguan." }, 500); }
});
function json(payload: unknown, status = 200) { return new Response(JSON.stringify(payload), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } }); }
